{
  server_files_dir:: "server_files_dir",
  model_name:"gpt2-medium",
  device:"cpu",
  server_ip:"10.229.130.18",
  server_port:8888,
  elastic_ip:"127.0.0.1",
  elastic_port:"9300",
  react_ip:"10.229.130.18",
  react_port:8889,
  streamlit_ip:"10.229.130.18",
  streamlit_port:8890,
  top_k_tokens_for_ui:10,
  top_k_for_elastic:50,
  create_cluster_files:false,
  num_clusters:3000,
  num_layers:24,
  elastic_index:$.model_name+"_projections_docs",
  elastic_projections_path:$.server_files_dir + "values_logits_" + $.model_name +"_top_"+$.top_k_for_elastic + ".pkl",
  streamlit_cluster_to_value_file_path: $.server_files_dir + "cluster_to_value_" + $.model_name +"_num_clusters_"+$.num_clusters + ".pkl",
  streamlit_value_to_cluster_file_path: $.server_files_dir + "value_to_cluster_" + $.model_name +"_num_clusters_"+$.num_clusters + ".pkl",
}
